### ISSUE TITLE
Maestro: Display property mapping in Layer editor does not match the generated XML

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-maestro#16]
Original Link: https://trac.osgeo.org/mapguide/ticket/2747

Per this thread: ​http://osgeo-org.1560.x6.nabble.com/Out-of-Order-SelectionPanel-js-td5288902.html

I tried reproducing the problem with data provided by Gordon. It turns out that the layer properties I'm selecting to show does not match the generated XML in terms of display order.

**Comment by jumpinjackie** [comment]
I can't reproduce this anymore

**Comment by RenoSun** [comment]
Hi Jackie,

Are there any ways to fix the same problem with AIMS 2017 (MapGuide 3.1.1.4601)?

http://osgeo-org.1560.x6.nabble.com/AIMS-2014-to-AIMS-2017-Selection-Panel-Display-Order-Issues-td5346401.html

Thank you very much!

**Comment by RenoSun** [comment]
Actually the Ajax Viewer has the same <LayerMetadata> with the same order that the data connection configuration XML has, but under <Feature> ... it responded the correct order of both label names, and values.
![image](https://user-images.githubusercontent.com/5566783/34014287-7dcdf84a-e0cf-11e7-949c-48c181580008.png)

![image](https://user-images.githubusercontent.com/5566783/34014305-8ce22356-e0cf-11e7-8961-89dcd5cf662b.png)

![image](https://user-images.githubusercontent.com/5566783/34014339-a42c7778-e0cf-11e7-894f-83bb1a25ce2d.png)

![image](https://user-images.githubusercontent.com/5566783/34014367-bd1475a6-e0cf-11e7-90c3-e12e19b1fdcc.png)

However, it's able to displayed the correct feature info.

Also, it's the correct order of the label and value under <Feature> response by using Fusion too.

Any codes that I may change in order to display the content with the order under <Feature>????

**Comment by RenoSun** [comment]
Temporary solution here for this problem with Fusion users:

under FusionSF.js:

convertExtendedFeatureInfo: function (efi) {
...
var layerMeta = selLayer.LayerMetadata[0];
//add this
var layerFeature = selLayer.Feature[0];
...
var metaProp = layerMeta.Property[j];
//add this
var featureProp = layerFeature.Property[j]
...
//change metaProp.DisplayName[0] to following code
pvals.push(featureProp.Name[0]);
...
}
