### ISSUE TITLE
Oracle Provider for Mapguide on Linux

### ISSUE THREAD

**Issue by SatishBonala** [jumpinjackie/mapguide-maestro#40]
Hi Jackie,

My Server Configuration is as below:

1.	MapGuide Server 3.1.0,	Oracle Instant Client 11g  installed on  Centos 6.8 Server
2.	Oracle 11g  & Maestro 5.1 are on Windows Server 2012

I have successfully performed the following steps:

1. Connection established to Oracle database from Linux Server and retrieving the data using SQL
2. Connection established to Map Guide Server 3.1.0 on Linux with   Map Guide Maestro v 5.1

**Issue:** I am getting the following error when connecting to data source with OSGeo.KingOracle 4.1.0 provider in Maestro

The remote server returned an error: (559) MgFdoException.: 
An exception occurred in FDO component.
Error occurred in Feature Source (Session:45a446e8-6665-11e7-8000-00016c5a03b2_en_MTI3LjAuMC4x0AFC0AFB0AFA//b4ccab67-4b8f-4e64-bc2b-55bc4a3d8485.FeatureSource): An exception occurred in FDO component.
Failed to retrieve the third party exception mesage. This message may not be unicode compliant.

- MgFdoConnectionManager.Open() line 333 file FdoConnectionManager.cpp
- MgFdoConnectionManager.CacheFdoConnection() line 1097 file FdoConnectionManager.cpp
- MgFdoConnectionManager.Open() line 1089 file FdoConnectionManager.cpp
 (Cause: , Root Cause: )

- MgFeatureServiceHandler.ProcessOperation() line 83 file FeatureServiceHandler.cpp
- MgOpTestFeatureSourceConnection.Execute() line 100 file OpTestFeatureSourceConnection.cpp
- MgServerFeatureService.TestConnection() line 244 file ServerFeatureService.cpp
- MgFdoConnectionManager.Open() line 366 file FdoConnectionManager.cpp
	The remote server returned an error: (559) MgFdoException.

Q1. Is sl-king fdo provider for oracle supported on Linux? 

If yes, Please share documents, urls, help manual to create layers in Maestro using SL-King FDO Provider for Oracle and display the layers using Mapguide Server.

If No, please suggest alternative to create layers in Maestro any other FDO Provider for Oracle and display the layers using Mapguide Server.

Thanks
Satish Bonala

**Comment by jumpinjackie** [comment]
The King Oracle provider does not work on Linux because of windows-specific assumptions around strings that are used.

https://trac.osgeo.org/fdo/ticket/562

Your only practical alternative would be to re-compile FDO's copy of GDAL with OCI driver support linked to your copy of the Oracle Instant Client SDK and replace the existing gdal binaries in `/usr/local/fdo-x.y.z` afterwards. From here, you would use the OGR FDO provider using the OCI data source as your Feature Sources to create layers/maps from.

Please use the mapguide-users (or fdo-users) mailing lists for such questions in the future. This is not related to Maestro at all.
